# Generated by Django 5.1.2 on 2024-10-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.CharField(max_length=30, null=True)),
                ('mecanismo', models.CharField(max_length=30, null=True)),
                ('tipoCorrea', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reloj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
                ('Filtro', models.ManyToManyField(to='tiendaRelojesAPP.filtro')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioCompra', models.FloatField()),
                ('Reloj', models.ManyToManyField(to='tiendaRelojesAPP.reloj')),
            ],
        ),
    ]
