# Generated by Django 5.1.2 on 2024-10-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaRelojesAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filtro',
            name='mecanismo',
        ),
        migrations.RemoveField(
            model_name='filtro',
            name='tipoCorrea',
        ),
        migrations.AddField(
            model_name='filtro',
            name='tipo_correa',
            field=models.CharField(choices=[('Acero', 'Acero'), ('Cuero', 'Cuero'), ('Tela', 'Tela')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='filtro',
            name='tipo_visualizacion',
            field=models.CharField(choices=[('Digital', 'Digital'), ('Analogico', 'Analógico')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='precio',
            field=models.CharField(choices=[('0-100', '0 a 100€'), ('100-500', '100 a 500€'), ('500+', 'Más de 500€')], max_length=30, null=True),
        ),
    ]
