# Generated by Django 5.1.2 on 2024-11-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaRelojesAPP', '0003_remove_compra_reloj_remove_reloj_filtro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reloj',
            name='filtro',
        ),
    ]
