# Generated by Django 5.1.2 on 2024-12-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaRelojesAPP', '0005_reloj_fotourl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='reloj',
        ),
        migrations.AddField(
            model_name='compra',
            name='relojes',
            field=models.ManyToManyField(related_name='compras', to='tiendaRelojesAPP.reloj'),
        ),
    ]
