# Generated by Django 5.1.2 on 2024-12-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaRelojesAPP', '0006_remove_compra_reloj_compra_relojes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='precioCompra',
            field=models.FloatField(editable=False),
        ),
    ]
