# Generated by Django 5.1.2 on 2024-12-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaRelojesAPP', '0007_alter_compra_preciocompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='precioCompra',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
